# SPDX-FileCopyrightText: The pasejo Authors
# SPDX-License-Identifier: 0BSD

version = 1

[[annotations]]
path = "tests/cmd/**"
precedence = "override"
SPDX-FileCopyrightText = "The pasejo Authors"
SPDX-License-Identifier = "0BSD"
