# SPDX-FileCopyrightText: The pasejo Authors
# SPDX-License-Identifier: 0BSD

name: Verify Commits
on:
  pull_request:
    branches: [ main ]
jobs:
  check:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust Target
        run: rustup target add ${{ matrix.target }}
      - name: Check Code
        run: cargo check --target ${{ matrix.target }}
      - name: Test Code
        run: cargo test --target ${{ matrix.target }}
