# SPDX-FileCopyrightText: The pasejo Authors
# SPDX-License-Identifier: 0BSD

name: Verify Commits
on:
  pull_request:
    branches: [ main ]
jobs:
  check:
    name: Check ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            apt_packages: ""
          - target: x86_64-apple-darwin
            os: macos-latest
            apt_packages: ""
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            apt_packages: gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            apt_packages: ""
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            apt_packages: gcc-mingw-w64-x86-64
          - target: aarch64-pc-windows-msvc
            os: windows
            apt_packages: ""
          - target: x86_64-pc-windows-msvc
            os: windows
            apt_packages: ""
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust Target
        run: rustup target add ${{ matrix.target }}
      - name: Install additional packages
        if: matrix.apt_packages != ''
        run: sudo apt-get install --yes --no-install-recommends ${{ matrix.apt_packages }}
      - name: Check Code
        run: cargo check --release --target ${{ matrix.target }}
      - name: Test Code
        run: cargo test
      - name: Build Code
        run: cargo build --release --target ${{ matrix.target }}
